### ISSUE TITLE
where is the Uncompressed code ?

### ISSUE THREAD

**Issue by myyan** [wanglingsong/ERC20ExchangeReactUI#1]
hi guys , i want to research the code , but it's compressed , so can you show me the Uncompressed code , thanks
![image](https://user-images.githubusercontent.com/10210390/42490677-2cb2cb20-8444-11e8-9598-b853c2e8dc77.png)

**Comment by wanglingsong** [comment]
May I know what kind of research you want to do? If you are really interested in this project, you can send me a email.
